### ISSUE TITLE
[FA - 03]Casos de Uso

### ISSUE THREAD

**Issue by Gabriielfeliciano** [Gabriielfeliciano/SiteFA#3]
- [x] Fluxograma do Cliente

- [x] Fluxograma do Dono

- [x] Fluxograma do não Cliente

**Comment by LFirmiano** [comment]
Apesar de ter um fluxograma feito, coloquei como "Fazendo" porque não ta especificado cada coisa no fluxograma do Cliente e da Empresa

**Comment by Gabriielfeliciano** [comment]
ok
