### ISSUE TITLE
[FA - 06]Plugin de conexão de SQL para o Wordpress

### ISSUE THREAD

**Issue by Gabriielfeliciano** [Gabriielfeliciano/SiteFA#6]
- [x] Procurar plugin que receba PostgreSQL.

- [x] Ver como conectar ao site.

- [x] Fazer um Banco de dados de teste.

**Comment by LFirmiano** [comment]
Não consegui fazer o teste ainda, por conta da questão do estágio., mas  vou tentar fazer ainda hoje!

**Comment by Gabriielfeliciano** [comment]
Ok, qualquer coisa passa pra outra Sprint
